name: Railway Auto-Deploy
on:
  push:
    branches:
      - main
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        uses: railwayapp/starters-action@v1.x
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
